version: "3.7"

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      NODE_ENV: run
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      NODE_ENV: run
      MONGO_DB_NAME: weather-metrics
    volumes:
      - ./backend/src:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - factorial
  mongo:
    image: mongo:5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - factorial
networks:
  factorial:
