version: "3.7"

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    command: npm run dev
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: run
      MONGO_DB_NAME: weather-metrics
    networks:
      - factorial
  front:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: npm run start:production
    depends_on:
      - api
    ports:
      - 3001:3001
    networks:
      - factorial
  mongo:
    image: mongo:5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - factorial
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - factorial
networks:
  factorial:
